#!/bin/sh
#
# $FreeBSD: head/net-p2p/rslsync/files/rslsync.in 469847 2018-05-14 02:55:52Z knu $
#
# PROVIDE: rslsync
# REQUIRE: LOGIN,networking
# KEYWORD: 
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# rslsync_enable (bool):        Set to NO by default.
#                               Set it to YES to enable it.
# rslsync_user:                 The user account rslsync daemon runs as
#                               what you want it to be. It uses 'rslsync'
#                               user by default. Do not sets it as empty or it
#                               will run as root.
# rslsync_group:                The group account rslsync daemon runs as
#                               what you want it to be. It uses 'rslsync'
#                               group by default. Do not sets it as empty or it
#                               will run as wheel.

. /etc/rc.subr

name="rslsync"
rcvar="${name}_enable"
command="/usr/local/bin/${name}"
command_args="--config /usr/local/etc/${name}.conf"
appPid="/var/run/${name}/${name}.pid"
managerPid="/var/run/${name}.manager.pid"
logFile="/var/log/${name}.log"

start_cmd="daemon_start"
stop_cmd="daemon_stop"
status_cmd="daemon_status"
start_precmd="daemon_prestart"

: ${daemon_user:="${name}"}
: ${daemon_group:="${name}"}

daemon_prestart() {
        if [ ! -d ${pidfile%/*} ]; 
        then
                install -d -o ${daemon_user} -g ${daemon_group} ${pidfile%/*}
        fi
}

daemon_start() {
    /usr/sbin/daemon -P ${managerPid} -p ${appPid} -r -f -S -o ${logFile} -u ${daemon_user} ${command}
}

daemon_stop() {
    if [ -e "${managerPid}" ]; 
    then
        kill -s TERM `cat ${managerPid}`
    else
        echo "${name} is not running"
    fi
}

daemon_status() {
    if [ -e "${appPid}" ]; 
    then
        echo "${name} is running as pid `cat ${appPid}`, with daemon manager (pid `cat ${managerPid}`)"
    else
        echo "${name} is not running"
    fi
}

load_rc_config ${name}
: ${rcvar:="NO"}

run_rc_command "$1"
