#!/bin/sh
#
# $FreeBSD: head/net-p2p/rslsync/files/rslsync.in 469847 2018-05-14 02:55:52Z knu $
#
# PROVIDE: rslsync
# REQUIRE: LOGIN,networking
# KEYWORD: 
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# rslsync_enable (bool):        Set to NO by default.
#                               Set it to YES to enable it.
# rslsync_user:                 The user account rslsync daemon runs as
#                               what you want it to be. It uses 'rslsync'
#                               user by default. Do not sets it as empty or it
#                               will run as root.
# rslsync_group:                The group account rslsync daemon runs as
#                               what you want it to be. It uses 'rslsync'
#                               group by default. Do not sets it as empty or it
#                               will run as wheel.

. /etc/rc.subr

name="rslsync"
rcvar="${name}_enable"
command="/usr/local/bin/${name}"
command_args="--config /usr/local/etc/${name}.conf"
pidfile="/var/run/${name}/${name}.pid"

start_cmd="deamon_start"
stop_cmd="deamon_stop"
status_cmd="deamon_status"
start_precmd="deamon_prestart"

: ${deamon_user:="${name}"}
: ${deamon_group:="${name}"}

deamon_prestart() {
        if [ ! -d ${pidfile%/*} ]; 
        then
                install -d -o ${deamon_user} -g ${deamon_group} ${pidfile%/*}
        fi
}

deamon_start() {
    /usr/sbin/daemon -P ${pidfile} -r -f -u $deamon_user $command
}

deamon_stop() {
    if [ -e "${pidfile}" ]; 
    then
        kill -s TERM `cat ${pidfile}`
    else
        echo "${name} is not running"
    fi
}

deamon_status() {
    if [ -e "${pidfile}" ]; 
    then
        echo "${name} is running as pid `cat ${pidfile}`"
    else
        echo "${name} is not running"
    fi
}

load_rc_config ${name}
: ${rslsync_enable:="NO"}

run_rc_command "$1"
